// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/madad-landing/Editorial.tsx": () => import("../components/mockups/madad-landing/Editorial.tsx"),
  "./components/mockups/madad-landing/ModernSplit.tsx": () => import("../components/mockups/madad-landing/ModernSplit.tsx")
};
