/* Madad — Panduan Mata Pelajaran Al-Azhar
   Panduan cara pakai AI untuk setiap mata pelajaran,
   bukan menyediakan AI-nya.
*/

const MAPEL_GUIDES = [
  /* ──── FIQH ──── */
  {
    id: "fiqh",
    subject: "Fiqh",
    arabic: "الفِقْهُ",
    faculty: "syariah",
    icon: "layers",
    aiId: "claude",
    aiName: "Claude",
    aiBy: "Anthropic",
    aiColor: "#D97757",
    aiLogo: "/assets/logo-claude.png",
    tagline: "Analisis qoul, tarjih mazhab, bedah dalil",
    description: "Belajar Fiqh berarti membandingkan pendapat, memahami dalil, dan bisa men-tarjih. Claude sangat cocok untuk ini.",
    whyThisAI: "Claude unggul dalam membaca teks panjang dan melakukan penalaran bertingkat — ideal untuk Fiqh yang membutuhkan perbandingan pendapat ulama dengan mempertimbangkan dalil dan konteks sekaligus. Claude juga sangat baik dalam menjelaskan perbedaan mazhab secara sistematis tanpa menyederhanakan terlalu jauh.",
    useCases: [
      "Bandingkan qoul 4 mazhab tentang satu masalah lengkap dengan dalil",
      "Minta analisis wajh istidlal dari sebuah ayat atau hadith",
      "Simulasi tanya-jawab persiapan munaqasyah",
      "Minta penjelasan istilah ushuliyyah dalam konteks Fiqh praktis",
      "Bantu susun outline makalah Fiqh dengan kerangka Azhari",
    ],
    steps: [
      { n: 1, title: "Buka Claude.ai", desc: "Kunjungi claude.ai. Model Claude 3.5 Sonnet (gratis) sudah lebih dari cukup untuk sesi belajar Fiqh harian." },
      { n: 2, title: "Beri konteks Azhari", desc: "Mulai sesi dengan: 'Aku mahasiswa Al-Azhar Syariah, sedang belajar Fiqh Muqaran. Bantu aku memahami [topik] dengan pendekatan ilmiah Azhari.' Konteks ini penting agar jawaban Claude lebih relevan." },
      { n: 3, title: "Minta perbandingan mazhab", desc: "Gunakan prompt perbandingan di bawah. Jangan hanya tanya 'apa hukumnya?' — tanya 'apa perbedaan mazhab dan mengapa mereka berbeda?'" },
      { n: 4, title: "Perdalam dengan dialog", desc: "Setelah dapat jawaban, lanjutkan: 'Apa yang membuat wajh istidlal Syafi'i lebih kuat di sini?' atau 'Ada ulama mutaakhkhirin yang mentarjih pendapat Hanafi?' Buat dialog, bukan one-shot." },
      { n: 5, title: "Catat ke Kurasah", desc: "Klik tombol ✏️ (Quick Note) untuk langsung catat poin penting ke Kurasahmu. Pilih tag 'Fiqh' supaya mudah dicari." },
    ],
    prompts: [
      { label: "Perbandingan 4 Mazhab", text: "Aku mahasiswa Al-Azhar Syariah. Jelaskan perbedaan pendapat 4 mazhab tentang [MASALAH FIQH]. Format: 1) Pendapat tiap mazhab (1-2 kalimat), 2) Dalil utama masing-masing, 3) Wajh istidlal singkat, 4) Pendapat yang rajih menurut jumhur. Gunakan istilah Arab yang tepat." },
      { label: "Analisis Dalil", text: "Bantu aku menganalisis dalil berikut dalam konteks Fiqh: [AYAT/HADITH]. Jelaskan: 1) Cara ulama Syafi'iyah menggunakan dalil ini, 2) Apakah ada mukhaalif yang berdalil berbeda, 3) Bagaimana cara al-jam' jika ada ta'arudh apparent." },
      { label: "Simulasi Munaqasyah", text: "Aku akan munaqasyah tentang [TOPIK FIQH]. Berperankan sebagai dosen penguji yang kritis. Ajukan 5 pertanyaan mendalam satu per satu, tunggu jawabanku, lalu koreksi dan tambahkan. Mulai dari pertanyaan definisi dan tahdid al-maudhu'." },
    ],
    tips: [
      "Selalu minta Claude menyebut nama kitab dan pengarang — bukan sekadar 'menurut ulama Syafi'iyah'.",
      "Jika Claude memberikan kutipan yang meragukan, tanyakan: 'Di kitab mana persis dan halamannya?' Ini memaksanya berhati-hati.",
      "Verifikasi kutipan penting di kitab aslinya. Claude kuat di analisis, tapi kadang salah di detail teks Arab.",
    ],
  },

  /* ──── USHUL FIQH ──── */
  {
    id: "ushul",
    subject: "Ushul Fiqh",
    arabic: "أُصُولُ الفِقْهِ",
    faculty: "syariah",
    icon: "bookOpen",
    aiId: "chatgpt",
    aiName: "ChatGPT",
    aiBy: "OpenAI",
    aiColor: "#10A37F",
    aiLogo: "/assets/logo-chatgpt.png",
    tagline: "Drill kaidah, latihan istidlal, aplikasi ushul",
    description: "Ushul Fiqh penuh kaidah dan teori. ChatGPT sangat baik untuk drill interaktif dan menguji pemahaman kaidah secara bertahap.",
    whyThisAI: "ChatGPT unggul dalam gaya diskusi interaktif dan drill soal — sangat tepat untuk Ushul Fiqh yang membutuhkan latihan menerapkan kaidah ke kasus-kasus praktis. ChatGPT juga responsif terhadap gaya dialog yang membangun pemahaman step by step.",
    useCases: [
      "Latihan soal kaidah Ushuliyyah (misal: al-amr lil-wujub, al-nahy lil-tahrim)",
      "Minta contoh tathbiq (aplikasi) kaidah ke kasus Fiqh nyata",
      "Drill perbedaan mazhab dalam usul (misal: kehujjahan qiyas, Istishab)",
      "Latihan menentukan dilalah lafadz dari teks dalil",
      "Minta ringkasan bab yang akan diujikan besok",
    ],
    steps: [
      { n: 1, title: "Buka ChatGPT", desc: "Kunjungi chat.openai.com. Model GPT-4o (gratis dengan batasan) sudah sangat baik untuk Ushul Fiqh." },
      { n: 2, title: "Beri konteks spesifik", desc: "Mulai dengan: 'Aku sedang belajar Ushul Fiqh di Al-Azhar. Bantu aku menguasai kaidah [NAMA KAIDAH] dengan cara interaktif.' Ini mengaktifkan mode tutor ChatGPT." },
      { n: 3, title: "Minta drill kaidah", desc: "Gunakan prompt drill di bawah. Jawab soal satu per satu — jangan lihat jawaban dulu. Ini yang membantu hafalan kaidah jadi kuat." },
      { n: 4, title: "Minta aplikasi ke kasus", desc: "Setelah paham kaidah secara teori, tanya: 'Berikan 3 contoh penerapan kaidah ini dalam Fiqh Ibadah dan 2 contoh dalam Fiqh Muamalat.' Ini memperkuat pemahaman kontekstual." },
      { n: 5, title: "Buat ringkasan penutup", desc: "Di akhir sesi, minta: 'Ringkaskan semua yang kita diskusikan dalam 5 poin bullet untuk aku simpan.' Lalu catat ke Kurasah." },
    ],
    prompts: [
      { label: "Drill Kaidah", text: "Aku belajar Ushul Fiqh Al-Azhar. Buat 10 soal latihan tentang kaidah [NAMA KAIDAH USHULIYYAH]. Tampilkan soal saja dulu tanpa jawaban. Aku akan jawab satu per satu, lalu kamu koreksi dan jelaskan yang salah." },
      { label: "Aplikasi Kaidah ke Kasus", text: "Jelaskan kaidah [KAIDAH USHUL] dengan cara berikut: 1) Definisi kaidah dalam bahasa sederhana, 2) Contoh tathbiq di Fiqh Ibadah, 3) Contoh tathbiq di Fiqh Muamalat, 4) Apakah ada pengecualian (mustathna) yang perlu diketahui mahasiswa Azhar." },
      { label: "Perbedaan Mazhab dalam Ushul", text: "Jelaskan perbedaan mazhab Syafi'i dan Hanafi dalam masalah [TOPIK USHUL seperti: kehujjahan hadith ahad, qiyas, istishab]. Sertakan implikasi perbedaan ini dalam Fiqh praktis dengan contoh konkret." },
    ],
    tips: [
      "Gunakan ChatGPT sebagai 'partner drill' — jangan hanya minta penjelasan, tapi minta dia menguji kamu.",
      "Setelah drill, minta 'kartu rangkuman' dalam format tabel: Kaidah | Definisi | Contoh | Pengecualian.",
      "Untuk hafalan matan Ushul (misal Waraqat), gunakan ChatGPT dengan mode tasmi' — lihat panduan Hafalan.",
    ],
  },

  /* ──── HADITH ──── */
  {
    id: "hadith",
    subject: "Hadith & Musthalah",
    arabic: "الحَدِيثُ وَمُصْطَلَحُهُ",
    faculty: "ushuluddin",
    icon: "search",
    aiId: "perplexity",
    aiName: "Perplexity",
    aiBy: "Perplexity AI",
    aiColor: "#1FB6B6",
    aiLogo: "/assets/logo-perplexity.png",
    tagline: "Takhrij, telusur sanad, klasifikasi hadith",
    description: "Takhrij dan analisis sanad butuh pencarian sumber yang tertelusur. Perplexity bisa melakukan ini dengan menyertakan referensi nyata.",
    whyThisAI: "Perplexity adalah AI berbasis pencarian web yang selalu menyertakan sumber — sangat penting dalam Hadith di mana verifikasi referensi adalah keharusan. Untuk analisis konseptual Musthalah yang lebih dalam, kombinasikan dengan Claude.",
    useCases: [
      "Telusur takhrij hadith: ada di kitab mana saja dan dengan sanad apa",
      "Cari klasifikasi hadith (shahih/hasan/dhaif) beserta alasan ulama",
      "Cari penjelasan tentang perawi hadith tertentu (jarh wa ta'dil)",
      "Minta ringkasan istilah-istilah Musthalah beserta contohnya",
      "Cari perbandingan pendapat ulama tentang status sanad hadith",
    ],
    steps: [
      { n: 1, title: "Buka Perplexity.ai", desc: "Kunjungi perplexity.ai. Gunakan versi gratis — sudah cukup untuk pencarian hadith dan Musthalah." },
      { n: 2, title: "Aktifkan mode Academic", desc: "Di bar pencarian Perplexity, pilih filter 'Academic' untuk mendapatkan sumber yang lebih terpercaya dan terverifikasi." },
      { n: 3, title: "Takhrij dengan konteks lengkap", desc: "Gunakan prompt takhrij di bawah. Sertakan teks hadith yang kamu punya — semakin lengkap teksnya, semakin akurat hasilnya." },
      { n: 4, title: "Verifikasi sumber", desc: "Perplexity selalu menyertakan link sumber. Klik dan verifikasi — ini kebiasaan ilmiah yang harus dilatih sejak awal." },
      { n: 5, title: "Untuk Musthalah, pakai Claude", desc: "Untuk analisis konseptual Musthalah (misal: perbedaan Shahih li dzatihi vs li ghairihi), pindah ke Claude yang lebih baik untuk penjelasan mendalam." },
    ],
    prompts: [
      { label: "Takhrij Hadith", text: "Lakukan takhrij untuk hadith berikut: [TEKS HADITH]. Temukan: 1) Di kitab mana saja hadith ini tercantum, 2) Jalur sanad utamanya, 3) Status hadith (shahih/hasan/dhaif) menurut ulama hadith terkemuka, 4) Kalau ada ikhtilaf dalam penilaian, sebutkan. Sertakan sumber yang bisa diverifikasi." },
      { label: "Analisis Perawi", text: "Cari informasi tentang perawi hadith bernama [NAMA PERAWI] dalam ilmu Jarh wa Ta'dil. Jelaskan: 1) Siapa dia dan kapan hidup, 2) Bagaimana penilaian ulama tentangnya (tsiqah/dhaif/dll), 3) Ulama mana yang memuji dan mencela, 4) Pengaruhnya terhadap hadith-hadith yang ia riwayatkan." },
      { label: "Istilah Musthalah", text: "Jelaskan istilah [ISTILAH MUSTHALAH HADITH] dalam ilmu Hadith. Berikan: 1) Definisi teknis yang dipakai ulama Hadith, 2) Perbedaannya dengan istilah yang mirip, 3) Contoh hadith yang masuk kategori ini, 4) Referensi dari kitab Musthalah klasik." },
    ],
    tips: [
      "Perplexity bukan kitab Hadith — gunakan hasilnya sebagai petunjuk awal, lalu verifikasi di Maktabah Syamilah atau sumber primer.",
      "Untuk takhrij yang serius, Perplexity adalah starting point, bukan ending point.",
      "Kalau butuh penjelasan Musthalah yang mendalam (bukan pencarian), Claude lebih baik.",
    ],
  },

  /* ──── TAFSIR ──── */
  {
    id: "tafsir",
    subject: "Tafsir & Ulum Al-Quran",
    arabic: "التَّفْسِيرُ وَعُلُومُ القُرْآنِ",
    faculty: "ushuluddin",
    icon: "quote",
    aiId: "claude",
    aiName: "Claude",
    aiBy: "Anthropic",
    aiColor: "#D97757",
    aiLogo: "/assets/logo-claude.png",
    tagline: "Analisis tafsir, perbandingan mufassir, ulum quran",
    description: "Memahami perbedaan pendekatan mufassir dan kaidah Ulum Al-Quran membutuhkan analisis mendalam yang menjadi kekuatan Claude.",
    whyThisAI: "Claude sangat baik untuk membandingkan pendekatan tafsir dari berbagai mufassir — dari Tafsir Thabari hingga Ibn Katsir hingga Zamakhsyari — sambil mempertimbangkan konteks dan metodologi masing-masing. Claude juga baik untuk menjelaskan konsep-konsep Ulum Al-Quran yang saling berkaitan.",
    useCases: [
      "Bandingkan tafsir ayat dari beberapa mufassir klasik",
      "Analisis sebab nuzul dan pengaruhnya terhadap makna ayat",
      "Minta penjelasan konsep Ulum Al-Quran (nasikh-mansukh, muhkam-mutasyabih)",
      "Diskusi tentang pendekatan tafsir bil-ma'tsur vs bil-ra'yi",
      "Bantu analisis I'jaz Quran dari aspek balaghah atau ilmiah",
    ],
    steps: [
      { n: 1, title: "Buka Claude.ai", desc: "Kunjungi claude.ai. Gunakan Claude 3.5 Sonnet untuk sesi Tafsir — kapasitas panjang konteksnya sangat membantu saat membahas ayat-ayat panjang." },
      { n: 2, title: "Sebutkan ayat dan konteks", desc: "Mulai dengan menyebutkan ayat lengkap beserta surahnya, lalu konteks belajar: 'Aku mahasiswa Tafsir Al-Azhar, sedang mengkaji [QS X:Y]. Bantu aku memahami tafsirnya dari berbagai perspektif mufassir.'" },
      { n: 3, title: "Minta perbandingan mufassir", desc: "Gunakan prompt perbandingan di bawah. Minta Claude membandingkan minimal 3 mufassir dengan pendekatan berbeda (misal: Thabari untuk riwayah, Zamakhsyari untuk balaghah, Ibn Asyur untuk maqashid)." },
      { n: 4, title: "Tanya Ulum Al-Quran terkait", desc: "Setelah tafsir, eksplorasi: 'Apakah ada sebab nuzul untuk ayat ini? Bagaimana ulama mengklasifikasikan ayat ini (muhkam/mutasyabih)?' Ini mengaitkan Tafsir dengan Ulum Al-Quran." },
      { n: 5, title: "Catat dan simpan", desc: "Catat poin penting ke Kurasah dengan tag 'Tafsir'. Tulis juga pertanyaan yang muncul selama sesi untuk ditanyakan ke ustadz." },
    ],
    prompts: [
      { label: "Perbandingan Mufassir", text: "Aku mahasiswa Tafsir Al-Azhar. Bandingkan tafsir dari ayat ini: [QS SURAH:AYAT dengan teksnya]. Sertakan pendapat: 1) Al-Thabari (riwayah), 2) Ibn Katsir (atsar), 3) Al-Zamakhsyari (balaghah), 4) Al-Qurthubi (ahkam jika ada). Jelaskan perbedaan pendekatan masing-masing." },
      { label: "Konsep Ulum Al-Quran", text: "Jelaskan konsep [KONSEP ULUM QURAN seperti: nasikh mansukh / muhkam mutasyabih / asbab nuzul / I'jaz Quran] dengan cara: 1) Definisi yang dipakai ulama klasik, 2) Contoh konkret dari Al-Quran, 3) Implikasinya dalam penafsiran, 4) Perbedaan pendapat ulama jika ada." },
      { label: "Analisis Balaghah Ayat", text: "Analisis aspek balaghah dari ayat berikut: [TEKS AYAT]. Identifikasi: 1) Uslub yang digunakan (khabar/insya', hakiki/majazi), 2) Jika ada majaz atau isti'arah, jelaskan macamnya dan efeknya, 3) Bagaimana para ahli balaghah (seperti Zamakhsyari atau Jurjani) menganalisis keindahan ayat ini." },
    ],
    tips: [
      "Jangan puas dengan tafsir satu mufassir saja — manfaatkan kemampuan Claude untuk membandingkan pendekatan berbeda.",
      "Gunakan Claude untuk 'warm up' sebelum baca kitab tafsir aslinya — ini membantu otak lebih siap menyerap teks Arab panjang.",
      "Untuk mencari apakah ada hadith tentang sebab nuzul, pindah ke Perplexity yang lebih baik untuk pencarian sumber.",
    ],
  },

  /* ──── NAHWU ──── */
  {
    id: "nahwu",
    subject: "Nahwu & Sharaf",
    arabic: "النَّحْوُ وَالصَّرْفُ",
    faculty: "bahasa",
    icon: "pen",
    aiId: "chatgpt",
    aiName: "ChatGPT",
    aiBy: "OpenAI",
    aiColor: "#10A37F",
    aiLogo: "/assets/logo-chatgpt.png",
    tagline: "Drill i'rab, latihan sharaf, koreksi teks Arab",
    description: "Nahwu dan Sharaf butuh banyak latihan. ChatGPT sangat efektif untuk drill i'rab interaktif dan koreksi analisis kaidah.",
    whyThisAI: "ChatGPT sangat responsif untuk drill latihan — bisa generate soal i'rab, mengoreksi jawaban kamu, dan menjelaskan kaidah yang dilanggar secara langsung. Gaya dialog ChatGPT cocok untuk sesi latihan yang butuh feedback cepat dan berulang.",
    useCases: [
      "Drill latihan i'rab kalimat dari teks Arab",
      "Latihan tashrif fi'il (shahih, mu'tall, mudha'af)",
      "Koreksi teks Arab yang kamu tulis sendiri",
      "Tanya kaidah Nahwu yang membingungkan dengan contoh konkret",
      "Latihan membedakan fa'il, maf'ul, mubtada, khabar di teks asli",
    ],
    steps: [
      { n: 1, title: "Buka ChatGPT", desc: "Kunjungi chat.openai.com. GPT-4o sudah sangat baik untuk Nahwu dan Sharaf." },
      { n: 2, title: "Mulai sesi drill", desc: "Mulai dengan: 'Aku mahasiswa Bahasa Arab Al-Azhar. Bantu aku latihan i'rab. Berikan kalimat Arab satu per satu, aku akan analisis i'rabnya, kamu koreksi.' Ini yang paling efektif." },
      { n: 3, title: "Kerjakan satu per satu", desc: "Jawab setiap soal dengan lengkap: sebutkan kata, posisi i'rab, tanda i'rab, dan alasan kaidahnya. Jangan skip bagian kaidah — ini yang menguatkan pemahaman." },
      { n: 4, title: "Tanya kaidah dari kesalahan", desc: "Setiap kali salah, tanya: 'Kaidah apa yang berlaku di sini dan apa contoh lain dari kaidah yang sama?' Ini mengubah kesalahan jadi pelajaran." },
      { n: 5, title: "Latihan di teks nyata", desc: "Setelah drill kalimat buatan, minta: 'Berikan satu ayat Al-Quran atau 1 bait syi'r untuk aku i'rab.' Ini tingkatan yang lebih real." },
    ],
    prompts: [
      { label: "Drill I'rab Interaktif", text: "Aku mahasiswa Bahasa Arab Al-Azhar, sedang latihan i'rab. Berikan satu kalimat Arab tingkat menengah untuk aku analisis. Aku akan sebut: kata per kata, posisi i'rab, tanda i'rab, dan kaidahnya. Setelah aku jawab, koreksi dan jelaskan yang salah. Lalu berikan kalimat berikutnya." },
      { label: "Latihan Tashrif", text: "Bantu aku latihan tashrif fi'il. Berikan fi'il berikut: [FI'IL MUJARRAD] — minta aku tashrif untuk: 1) Fi'il madhi (mukadzdzar), 2) Fi'il mudhari (marfu', mansub, majzum), 3) Fi'il amr, 4) Isim fa'il dan maf'ul. Koreksi per bagian dan jelaskan pola yang berlaku." },
      { label: "Koreksi Tulisan Arab", text: "Koreksi tulisan Arab berikut dari sisi Nahwu dan Sharaf: [TEKS ARABMU]. Tandai setiap kesalahan, sebutkan kaidah yang dilanggar, dan berikan versi yang benar. Format: [Salah] → [Benar] + (Kaidah: ...)." },
    ],
    tips: [
      "Jangan hanya minta penjelasan kaidah — minta soal dan jawab dulu, baru minta koreksi. Ini jauh lebih efektif.",
      "Untuk i'rab teks Quran atau hadith yang panjang, paste langsung ke ChatGPT dan minta i'rab kata per kata.",
      "Setelah sesi drill, minta ringkasan kaidah yang sering kamu salah — ini jadi daftar prioritas murajaah.",
    ],
  },

  /* ──── AQIDAH ──── */
  {
    id: "aqidah",
    subject: "Aqidah & Ilmu Kalam",
    arabic: "العَقِيدَةُ وَعِلْمُ الكَلَامِ",
    faculty: "ushuluddin",
    icon: "shield",
    aiId: "claude",
    aiName: "Claude",
    aiBy: "Anthropic",
    aiColor: "#D97757",
    aiLogo: "/assets/logo-claude.png",
    tagline: "Bedah argumen, klasifikasi aliran, analisis tekstual",
    description: "Aqidah dan Kalam membutuhkan kemampuan bedah argumen filosofis. Claude sangat baik untuk ini.",
    whyThisAI: "Claude sangat handal dalam analisis argumen logis dan klasifikasi aliran pemikiran — dua hal yang menjadi inti Ilmu Kalam. Claude bisa menjelaskan perbedaan argumen Asy'ariyah, Maturidiyyah, dan Mu'tazilah dengan mempertimbangkan konteks dan nuansa masing-masing.",
    useCases: [
      "Bandingkan argumen aliran Asy'ariyah, Maturidiyyah, dan Mu'tazilah",
      "Analisis hujjah untuk sifat-sifat Allah (sifat khabariyyah, sifat fi'liyyah)",
      "Minta penjelasan klasifikasi bid'ah dan implikasinya",
      "Bedah argumen falsafi dalam konteks Kalam (misal: kosmologis, ontologis)",
      "Latihan menjelaskan Aqidah secara sistematis untuk makalah",
    ],
    steps: [
      { n: 1, title: "Buka Claude.ai", desc: "Gunakan Claude 3.5 Sonnet. Beri konteks: 'Aku mahasiswa Ushuluddin Al-Azhar, spesialisasi Aqidah/Kalam.' Ini membantu Claude memahami level akademis yang diharapkan." },
      { n: 2, title: "Framing topik dulu", desc: "Sebelum tanya detail, minta framing: 'Berikan peta besar topik [TOPIK AQIDAH]: aliran-aliran utama yang berpendapat, isu inti yang diperdebatkan, dan tokoh-tokoh kunci.' Ini memberi orientasi sebelum masuk detail." },
      { n: 3, title: "Gali argumen masing-masing", desc: "Setelah punya peta besar, gali lebih dalam per aliran: 'Apa argumen utama Asy'ariyyah di masalah ini? Apa dalil naqliy dan aqli yang mereka gunakan?'" },
      { n: 4, title: "Tantang dengan counter-argumen", desc: "Latih kemampuan berpikir kritis: 'Apa keberatan terkuat terhadap argumen Asy'ariyyah ini? Bagaimana mereka merespons keberatan itu?' Ini mempersiapkan untuk debat akademik." },
      { n: 5, title: "Sintesis dan catat", desc: "Minta sintesis: 'Rangkum perbedaan posisi dalam 3 poin kunci.' Catat ke Kurasah dengan tag 'Aqidah'." },
    ],
    prompts: [
      { label: "Perbandingan Aliran Kalam", text: "Aku mahasiswa Ushuluddin Al-Azhar, belajar Ilmu Kalam. Bandingkan posisi Asy'ariyyah, Maturidiyyah, dan Mu'tazilah tentang [TOPIK seperti: sifat Allah / af'al al-ibad / ru'yatullah]. Sertakan: 1) Posisi masing-masing, 2) Dalil yang digunakan, 3) Argumen utama, 4) Persamaan dan perbedaan Asy'ari-Maturidi secara spesifik." },
      { label: "Analisis Argumen", text: "Bantu aku menganalisis argumen berikut dalam konteks Ilmu Kalam: [ARGUMEN ATAU PERNYATAAN]. Identifikasi: 1) Premis-premis yang digunakan, 2) Struktur logika argumen ini, 3) Bagaimana ulama Asy'ariyyah akan meresponsnya, 4) Apakah ada kelemahan yang bisa dikritisi dari sudut pandang ortodoks Sunni." },
      { label: "Penjelasan Sifat Allah", text: "Jelaskan secara sistematis tentang sifat [SIFAT ALLAH] menurut Asy'ariyyah: 1) Klasifikasi sifat ini (dzatiyyah/ma'nawiyyah/fi'liyyah/khabariyyah), 2) Cara menetapkan sifat ini (dalil aqli dan naqli), 3) Bagaimana menjauhi ta'thil dan tasybiih dalam memahami sifat ini, 4) Posisi Maturidiyyah jika ada perbedaan." },
    ],
    tips: [
      "Gunakan Claude untuk membangun 'peta argumen' sebelum baca matan Aqidah — ini membantu orientasi.",
      "Pastikan kamu tidak hanya terima argumen Claude — tanya juga 'Apa kelemahan pandangan ini?' untuk berpikir kritis.",
      "Untuk dalil-dalil naqli (Quran/Hadith), verifikasi ke sumber primer karena Claude kadang tidak akurat dalam teks Arab.",
    ],
  },

  /* ──── BALAGHAH ──── */
  {
    id: "balaghah",
    subject: "Balaghah",
    arabic: "البَلَاغَةُ",
    faculty: "bahasa",
    icon: "sparkles",
    aiId: "claude",
    aiName: "Claude",
    aiBy: "Anthropic",
    aiColor: "#D97757",
    aiLogo: "/assets/logo-claude.png",
    tagline: "Analisis uslub, identifikasi majas, bedah keindahan",
    description: "Balaghah membutuhkan kemampuan merasakan keindahan bahasa sekaligus menganalisisnya secara teknis. Claude sangat baik di keduanya.",
    whyThisAI: "Claude unggul dalam analisis sastra dan linguistik — bisa mengidentifikasi majas, menjelaskan efek retoris, dan membandingkan uslub secara mendalam. Ini sangat cocok untuk Balaghah yang memadukan rasa dan analisis teknis.",
    useCases: [
      "Analisis uslub dan majas dalam ayat Al-Quran atau bait syi'r",
      "Identifikasi macam tasybiih, isti'arah, majaz mursal dalam teks",
      "Minta penjelasan konsep Balaghah (fashaahah, balaaghah, mashaadir)",
      "Latihan membuat analisis Balaghah untuk tugas",
      "Diskusi tentang I'jaz Quran dari sudut Balaghah",
    ],
    steps: [
      { n: 1, title: "Buka Claude.ai", desc: "Claude adalah pilihan terbaik untuk Balaghah. Kemampuannya dalam analisis bahasa Arab sastra jauh di atas AI lain." },
      { n: 2, title: "Berikan teks yang akan dianalisis", desc: "Paste teks Arab yang ingin dianalisis — ayat Quran, bait syi'r, atau prosa Arab. Makin lengkap teksnya, makin baik analisisnya." },
      { n: 3, title: "Minta analisis sistematis", desc: "Gunakan format yang terstruktur: identifikasi majas dulu, lalu efek retorisnya, lalu konteks. Prompt analisis di bawah sudah dirancang untuk ini." },
      { n: 4, title: "Tanya 'mengapa indah?'", desc: "Setelah analisis teknis, tanya: 'Mengapa pilihan uslub ini lebih efektif daripada cara ekspresi yang lebih langsung?' Ini mengembangkan dhauq (rasa) sastra." },
      { n: 5, title: "Latihan buat sendiri", desc: "Minta Claude memberikan kalimat Arab sederhana, lalu coba kamu sendiri mengidentifikasi unsur Balaghah-nya. Ini jauh lebih efektif dari sekedar membaca." },
    ],
    prompts: [
      { label: "Analisis Majas & Uslub", text: "Analisis aspek Balaghah dari teks Arab berikut: [TEKS ARAB]. Identifikasi: 1) Uslub khabar atau insya' dan tujuannya, 2) Semua majas yang ada (tasybiih, isti'arah, majaz mursal, kinayah) — sebutkan jenis dan sumber serta tujuannya, 3) Aspek fashaahah (kehalusan bahasa), 4) Secara keseluruhan, apa efek balaghiy yang dicapai teks ini." },
      { label: "Penjelasan Konsep Balaghah", text: "Jelaskan konsep [KONSEP BALAGHAH seperti: tasybiih baligh / isti'arah makniyyah / majaz mursal / asaaliib al-qasr] dengan: 1) Definisi teknis, 2) Unsur-unsur pembentuknya, 3) Contoh dari Al-Quran atau syi'r Arab klasik, 4) Perbedaannya dengan konsep yang mirip." },
      { label: "I'jaz Quran dari Balaghah", text: "Jelaskan aspek I'jaz Balaghiy dalam ayat berikut: [AYAT QURAN]. Analisis: 1) Keistimewaan pemilihan kata (mufradat), 2) Struktur kalimat dan efeknya, 3) Majas yang digunakan dan mengapa pilihan ini lebih kuat dari alternatif lain, 4) Bagaimana ulama Balaghah seperti Al-Jurjani menganalisis ayat ini." },
    ],
    tips: [
      "Untuk Balaghah, proses 'merasakan' sama pentingnya dengan hafalan — gunakan Claude untuk melatih keduanya.",
      "Setelah Claude menganalisis, coba tulis ulang teks tanpa majas — ini memperlihatkan betapa majas mengubah makna dan efek.",
      "Kumpulkan contoh-contoh analisis yang bagus ke Kurasah sebagai bank referensi untuk makalah.",
    ],
  },

  /* ──── MAKALAH ──── */
  {
    id: "makalah",
    subject: "Makalah Azhari",
    arabic: "البَحْثُ العِلْمِيُّ الأَزْهَرِيُّ",
    faculty: "umum",
    icon: "clipboard",
    aiId: "chatgpt",
    aiName: "ChatGPT",
    aiBy: "OpenAI",
    aiColor: "#10A37F",
    aiLogo: "/assets/logo-chatgpt.png",
    tagline: "Outline, drafting, editing gaya Azhari",
    description: "Menulis makalah ilmiah Azhari ada seninya. ChatGPT sangat membantu untuk outlining, drafting, dan editing dengan gaya akademis.",
    whyThisAI: "ChatGPT sangat baik untuk writing assistance — membantu menyusun outline yang logis, men-draft paragraf awal, dan memperbaiki gaya tulisan. Untuk makalah Azhari, ChatGPT bisa diarahkan untuk menggunakan gaya akademis Arab yang sesuai dengan standar Al-Azhar.",
    useCases: [
      "Susun outline makalah dari topik yang diberikan dosen",
      "Draft pendahuluan (muqaddimah) dengan gaya ilmiah",
      "Perbaiki gaya bahasa Arab makalah yang sudah kamu tulis",
      "Minta saran struktur argumen sebelum menulis",
      "Buat abstrak (mulakhkhas) dari makalah yang sudah selesai",
    ],
    steps: [
      { n: 1, title: "Buka ChatGPT", desc: "GPT-4o adalah yang terbaik untuk writing tasks. Jika tidak ada akses, Claude juga sangat baik untuk makalah." },
      { n: 2, title: "Jelaskan makalah secara detail", desc: "Sebelum minta bantuan, jelaskan: topik, tujuan, target pembaca, panjang yang diminta, dan gaya yang diharapkan (apakah Arab atau Indonesia). Ini menentukan kualitas output." },
      { n: 3, title: "Susun outline dulu", desc: "Jangan langsung minta draft — minta outline dulu. Review outline, diskusikan, baru setujui sebelum lanjut ke drafting." },
      { n: 4, title: "Draft per bagian", desc: "Minta draft satu bagian (bab atau sub-bab) sekaligus — jangan minta seluruh makalah sekaligus. Ini memberi kamu kontrol atas arah tulisan." },
      { n: 5, title: "Edit dan verifikasi", desc: "Selalu edit output ChatGPT dengan tangan kamu sendiri. Tambahkan perspektifmu, verifikasi fakta/kutipan, dan pastikan gaya sesuai standar Al-Azhar." },
    ],
    prompts: [
      { label: "Susun Outline Makalah", text: "Bantu aku menyusun outline makalah ilmiah tentang [TOPIK]. Konteks: makalah untuk mata kuliah [MATA KULIAH] di Al-Azhar, panjang sekitar [PANJANG]. Outline harus mencakup: muqaddimah, setidaknya 3 bab/fashl utama dengan sub-bab yang logis, dan khatimah. Sertakan poin-poin apa saja yang akan dibahas di setiap bagian." },
      { label: "Draft Muqaddimah", text: "Tulis draft muqaddimah makalah tentang [TOPIK] dalam bahasa Arab ilmiah. Muqaddimah harus mencakup: 1) Pembuka yang menarik (tarhiib), 2) Urgensi topik (ahamiyyah al-mawdhu'), 3) Tujuan penelitian (ahdaaf), 4) Metode penelitian (manhaj), 5) Struktur makalah (haikal al-buhuts). Gaya bahasa: akademis Azhari, hindari bahasa sehari-hari." },
      { label: "Perbaiki Tulisan Arab", text: "Perbaiki tulisan Arab berikut untuk makalah ilmiah: [TEKS ARABMU]. Perbaiki: 1) Kesalahan Nahwu dan Sharaf, 2) Gaya bahasa (jadikan lebih formal dan akademis), 3) Struktur kalimat yang kurang jelas, 4) Pilihan kata yang lebih tepat. Tampilkan versi perbaikan dan jelaskan perubahan utama." },
    ],
    tips: [
      "ChatGPT adalah asisten penulis, bukan penulis — kamu yang menentukan argumen dan perspektif, ChatGPT yang membantu ekspresinya.",
      "Untuk referensi dan sitasi, jangan mengandalkan ChatGPT — gunakan Perplexity atau buka langsung Maktabah Syamilah.",
      "Selalu proofread akhir secara manual — ChatGPT kadang menghasilkan kalimat Arab yang secara gramatikal aneh.",
    ],
  },

  /* ──── RISET ──── */
  {
    id: "riset",
    subject: "Riset & Referensi",
    arabic: "البَحْثُ وَالمَصَادِرُ",
    faculty: "umum",
    icon: "compass",
    aiId: "perplexity",
    aiName: "Perplexity",
    aiBy: "Perplexity AI",
    aiColor: "#1FB6B6",
    aiLogo: "/assets/logo-perplexity.png",
    tagline: "Cari sumber tertelusur, buku klasik, artikel akademik",
    description: "Riset akademis butuh sumber yang bisa diverifikasi. Perplexity adalah satu-satunya AI yang selalu menyertakan sumber nyata.",
    whyThisAI: "Perplexity adalah AI berbasis pencarian real-time yang selalu menyertakan sumber yang bisa diklik dan diverifikasi. Ini yang membedakannya dari AI lain untuk tugas riset — kamu tidak perlu khawatir apakah sumber itu ada atau tidak.",
    useCases: [
      "Cari buku/kitab klasik yang relevan dengan topik penelitian",
      "Temukan artikel akademik tentang topik keislaman kontemporer",
      "Verifikasi fakta dan angka sebelum dimasukkan ke makalah",
      "Cari pendapat ulama kontemporer tentang masalah tertentu",
      "Telusur siapa saja yang sudah menulis tentang topikmu (kajian terdahulu)",
    ],
    steps: [
      { n: 1, title: "Buka Perplexity.ai", desc: "Kunjungi perplexity.ai. Aktifkan filter 'Academic' untuk penelitian akademis, atau 'All' untuk pencarian umum tentang sumber Islam." },
      { n: 2, title: "Buat pertanyaan riset yang spesifik", desc: "Pertanyaan yang spesifik menghasilkan sumber yang lebih relevan. Bukan: 'buku tentang Fiqh' tapi 'buku Fiqh Muqaran tentang zakat kontemporer yang ditulis ulama abad 20'." },
      { n: 3, title: "Verifikasi semua sumber", desc: "Klik setiap link yang Perplexity berikan dan verifikasi kontennya. Jangan langsung masukkan ke makalah tanpa cek." },
      { n: 4, title: "Gunakan untuk kajian terdahulu", desc: "Untuk bab 'Dirasat Sabiqah', minta: 'Siapa saja yang sudah menulis penelitian akademik tentang [TOPIK]? Sebutkan judul, penulis, tahun, dan fokus penelitiannya.'" },
      { n: 5, title: "Kombinasikan dengan NotebookLM", desc: "Setelah dapat sumber dari Perplexity, upload PDF artikel/bab ke NotebookLM untuk analisis dan tanya-jawab mendalam dari sumber spesifik itu." },
    ],
    prompts: [
      { label: "Cari Sumber Akademik", text: "Cari sumber-sumber akademik (buku, jurnal, artikel) yang relevan dengan topik: [TOPIK PENELITIAN]. Spesifikasi: 1) Prioritaskan karya ulama Al-Azhar atau penulis Muslim terkemuka, 2) Sertakan karya dalam bahasa Arab dan Indonesia jika ada, 3) Sebutkan judul, penulis, penerbit, dan tahun untuk setiap sumber, 4) Sumber harus bisa diverifikasi." },
      { label: "Kajian Terdahulu", text: "Bantu aku menyusun 'Dirasat Sabiqah' (kajian penelitian terdahulu) untuk topik: [TOPIK MAKALAHKU]. Cari: 1) Minimal 3-5 penelitian terdahulu yang relevan, 2) Sebutkan fokus masing-masing penelitian, 3) Jelaskan apa yang membedakan penelitianku dari penelitian terdahulu tersebut." },
      { label: "Verifikasi Fakta", text: "Verifikasi fakta/informasi berikut yang akan aku masukkan ke makalah: [FAKTA ATAU PERNYATAAN]. Konfirmasi: apakah ini akurat? Dari sumber mana? Apakah ada data terbaru yang lebih tepat? Sertakan sumber yang bisa diklik." },
    ],
    tips: [
      "Perplexity adalah starting point riset, bukan ending point — gunakan sumbernya untuk menemukan bahan, lalu baca bahan aslinya.",
      "Untuk kitab klasik Islam, Perplexity kadang memberikan link ke archive.org atau al-maktaba.org — sangat berguna untuk akses teks asli.",
      "Kombinasikan dengan NotebookLM: Perplexity untuk menemukan sumber, NotebookLM untuk menganalisis sumber yang sudah kamu temukan.",
    ],
  },

  /* ──── HAFALAN ──── */
  {
    id: "hafalan",
    subject: "Hafalan Matan & Quran",
    arabic: "التَّحْفِيظُ وَالمُرَاجَعَةُ",
    faculty: "umum",
    icon: "refresh",
    aiId: "chatgpt",
    aiName: "ChatGPT",
    aiBy: "OpenAI",
    aiColor: "#10A37F",
    aiLogo: "/assets/logo-chatgpt.png",
    tagline: "Sesi tasmi' interaktif, murajaah, spaced repetition",
    description: "AI tidak menghafal untukmu — tapi bisa jadi partner tasmi' yang sabar dan tersedia 24 jam.",
    whyThisAI: "ChatGPT sangat baik untuk sesi tasmi' interaktif — bisa memberikan potongan ayat/matan, menunggu jawabanmu, memberikan petunjuk halus jika kamu stuck, dan mencatat mana yang perlu murajaah. Lebih fleksibel dari tasmi' ke teman karena bisa dilakukan kapan saja.",
    useCases: [
      "Sesi tasmi' murajaah Quran sebelum tidur",
      "Hafalan matan Ushul Fiqh (Waraqat, dll) dengan drill interaktif",
      "Buat jadwal murajaah berdasarkan tingkat kelancaran",
      "Latihan menghafal matan hadith Arba'in atau Bulugh",
      "Identifikasi ayat/matan yang paling sering lupa untuk prioritas murajaah",
    ],
    steps: [
      { n: 1, title: "Buka ChatGPT", desc: "Gunakan ChatGPT untuk sesi tasmi'. Beri konteks: berapa juz/halaman/matan yang ingin kamu murajaah, dan metode apa yang kamu mau (prompt awal atau akhir ayat)." },
      { n: 2, title: "Pilih mode tasmi'", desc: "Ada dua mode: 1) ChatGPT sebut awal ayat/matan, kamu lanjutkan. 2) Kamu sebutkan nomor ayat/bab, ChatGPT koreksi hafalanmu. Pilih sesuai preferensi." },
      { n: 3, title: "Murajaah satu per satu", desc: "Jangan minta sekaligus — minta satu ayat atau satu kalimat matan, jawab, baru lanjut. Ini memaksa otak benar-benar mengambil dari memori, bukan membaca." },
      { n: 4, title: "Catat yang ragu", desc: "Minta ChatGPT mencatat ayat/matan yang kamu ragu atau salah selama sesi. Di akhir, minta daftar lengkap untuk prioritas murajaah esok hari." },
      { n: 5, title: "Jadwalkan murajaah rutin", desc: "Minta ChatGPT membuat jadwal murajaah mingguan berdasarkan jumlah hafalan dan waktu tersedia. Simpan ke Kurasah sebagai reminder." },
    ],
    prompts: [
      { label: "Sesi Tasmi' Quran", text: "Aku mau murajaah hafalan Quran, mulai dari [SURAT/JUZ]. Mode: kamu sebutkan 3-5 kata pertama suatu ayat secara acak dalam rentang yang aku sebutkan, aku lanjutkan sampai akhir ayat. Jika aku ragu, beri petunjuk berupa 2 kata berikutnya saja. Di akhir sesi, beri daftar ayat yang perlu aku murajaah ulang." },
      { label: "Sesi Tasmi' Matan", text: "Aku menghafal matan [NAMA MATAN seperti: Waraqat / Arba'in Nawawiyah / Al-Jurumiyyah]. Lakukan sesi tasmi': sebutkan potongan pertama dari sebuah bagian, aku lanjutkan sampai akhir. Jika aku salah atau skip, koreksi dan catat. Di akhir, beri laporan: berapa yang lancar, berapa yang perlu murajaah." },
      { label: "Jadwal Murajaah", text: "Buat jadwal murajaah untuk hafalanku: Total hafalan: [JUMLAH JUZ/HALAMAN/MATAN]. Waktu tersedia per hari: [MENIT]. Target: murajaah semua dalam [PERIODE]. Buat jadwal mingguan yang realistis, sertakan rotasi untuk memastikan semua bagian mendapat giliran secara teratur." },
    ],
    tips: [
      "ChatGPT adalah partner tasmi', bukan guru mengaji — tetap prioritaskan tasmi' ke guru atau orang yang hafidz untuk validasi.",
      "Gunakan sesi ChatGPT untuk 'pre-tasmi' mandiri sebelum tasmi' resmi ke guru — ini menghemat waktu dan meningkatkan kualitas.",
      "Untuk matan yang panjang, mulai dari bagian yang paling lemah, bukan dari awal — ini lebih efisien.",
    ],
  },
];

window.MAPEL_GUIDES = MAPEL_GUIDES;
