import { sbConfig, sbHeaders, getAuthUser, resolveMember, newMemberCode, consumeQuota } from './_lib/member.js';
import { normalizePin } from './_lib/pin.js';
import { verifyUnsubToken, addOptout } from './_lib/email.js';
import {
  CHECKOUT_PLANS, mayarConfigured, checkoutBlockReason, createCheckout, getOwnedCheckout, refreshCheckout,
} from './_lib/payments.js';

// Identity comes from the Supabase (Google) access token. Existing members link their
// Google account once via action=redeem with a one-time activation PIN generated by admin.
// Member codes are internal IDs only — they were often shared, so they can't claim an account.

const MEMBER_FIELDS = 'code,name,email,status,expires_at,auth_user_id,activation_pin_expires_at';

const redeemAttempts = new Map();
const checkRedeemLimit = (key) => {
  const now = Date.now();
  const recent = (redeemAttempts.get(key) || []).filter(t => now - t < 15 * 60 * 1000);
  if (recent.length >= 10) return false;
  recent.push(now);
  redeemAttempts.set(key, recent);
  return true;
};

const parseBody = (req) => new Promise((resolve) => {
  let body = '';
  req.on('data', chunk => body += chunk);
  req.on('end', () => {
    try { resolve(JSON.parse(body || '{}')); }
    catch { resolve({}); }
  });
});

const toPublicMember = (m, user) => ({
  code:      m.code,
  name:      m.name || user.name || user.email.split('@')[0],
  email:     m.email || user.email,
  status:    m.status,
  expiresAt: m.expires_at,
  tier:      m.tier || 'library',
});

const touchLastLogin = (code) => {
  const { url, key } = sbConfig();
  fetch(`${url}/rest/v1/members?code=eq.${encodeURIComponent(code)}`, {
    method: 'PATCH',
    headers: sbHeaders(key, { Prefer: 'return=minimal' }),
    body: JSON.stringify({ last_login: new Date().toISOString() }),
  }).catch(e => console.warn('[login] last_login update failed:', e.message));
};

async function handleSession(user, res) {
  const member = await resolveMember(user);
  if (!member) return res.status(200).json({ ok: false, status: 'not_member', email: user.email });
  if (member.status !== 'active') return res.status(200).json({ ok: false, status: member.status });
  touchLastLogin(member.code);
  return res.status(200).json({ ok: true, member: toPublicMember(member, user) });
}

async function handleRedeem(req, user, res) {
  const ip = (req.headers['x-forwarded-for'] || '').split(',')[0].trim() || req.headers['x-real-ip'] || 'unknown';
  if (!checkRedeemLimit(`user:${user.id}`) || (ip !== 'unknown' && !checkRedeemLimit(`ip:${ip}`))) {
    return res.status(429).json({ ok: false, status: 'rate_limited' });
  }

  const pin = normalizePin((await parseBody(req)).pin);
  if (!pin) return res.status(400).json({ ok: false, status: 'invalid' });

  const current = await resolveMember(user);
  if (current?.status === 'active' && current.tier !== 'free') {
    return res.status(200).json({ ok: true, member: toPublicMember(current, user) });
  }
  // Pemilik akun gratis yang ternyata member lama: akun gratisnya dilepas lalu diganti member lama.
  const freeAccount = current?.status === 'active' && current.tier === 'free' ? current : null;

  const { url, key } = sbConfig();
  const rows = await fetch(
    `${url}/rest/v1/members?activation_pin=eq.${encodeURIComponent(pin)}&select=${MEMBER_FIELDS}&limit=1`,
    { headers: sbHeaders(key) }
  ).then(r => r.json());
  const row = Array.isArray(rows) ? rows[0] : null;

  if (!row) return res.status(200).json({ ok: false, status: 'not_found' });
  if (row.activation_pin_expires_at && new Date(row.activation_pin_expires_at) < new Date()) {
    return res.status(200).json({ ok: false, status: 'pin_expired' });
  }
  if (row.status !== 'active') return res.status(200).json({ ok: false, status: row.status });
  if (row.auth_user_id && row.auth_user_id !== user.id) {
    return res.status(200).json({ ok: false, status: 'already_linked' });
  }

  // Conditional on the PIN still being unused and the row unlinked, so two accounts racing can't both win.
  // The PIN is cleared in the same update, making it single-use.
  const link = (patch) => fetch(
    `${url}/rest/v1/members?code=eq.${encodeURIComponent(row.code)}&activation_pin=eq.${encodeURIComponent(pin)}&auth_user_id=is.null&select=${MEMBER_FIELDS}`,
    {
      method: 'PATCH',
      headers: sbHeaders(key, { Prefer: 'return=representation' }),
      body: JSON.stringify({
        auth_user_id: user.id,
        activation_pin: null,
        activation_pin_expires_at: null,
        last_login: new Date().toISOString(),
        ...patch,
      }),
    }
  );

  const patchFree = (body) => fetch(`${url}/rest/v1/members?code=eq.${encodeURIComponent(freeAccount.code)}`, {
    method: 'PATCH',
    headers: sbHeaders(key, { Prefer: 'return=minimal' }),
    body: JSON.stringify(body),
  });
  if (freeAccount) {
    const detached = await patchFree({ auth_user_id: null, email: null, status: 'disabled', notes: `Diganti member lama ${row.code}` });
    if (!detached.ok) return res.status(200).json({ ok: false, status: 'error' });
  }

  let r = await link(row.email ? {} : { email: user.email });
  if (!r.ok) r = await link({}); // email already used by another member row
  const linked = await r.json().catch(() => []);
  if (!Array.isArray(linked) || !linked[0]) {
    if (freeAccount) await patchFree({ auth_user_id: user.id, email: freeAccount.email, status: 'active', notes: 'Akun gratis' });
    return res.status(200).json({ ok: false, status: 'already_linked' });
  }

  return res.status(200).json({ ok: true, member: toPublicMember(linked[0], user) });
}

// Login Google tanpa bayar → akun gratis terbatas (tier 'free').
async function handleStartFree(req, user, res) {
  const current = await resolveMember(user);
  if (current) {
    if (current.status !== 'active') return res.status(200).json({ ok: false, status: current.status });
    return res.status(200).json({ ok: true, member: toPublicMember(current, user) });
  }
  // Maks 20 akun gratis baru per IP per hari (Vercel mengisi x-real-ip dengan IP asli pengunjung).
  const ip = String(req.headers['x-real-ip'] || (req.headers['x-forwarded-for'] || '').split(',')[0] || '').trim();
  if (ip && !(await consumeQuota(`IP-${ip}`.slice(0, 60), 'signup', 20))) {
    return res.status(429).json({ ok: false, status: 'rate_limited' });
  }

  const { url, key } = sbConfig();
  const now = new Date().toISOString();
  for (let attempt = 0; attempt < 5; attempt++) {
    const r = await fetch(`${url}/rest/v1/members?select=code,name,email,status,expires_at,tier`, {
      method: 'POST',
      headers: sbHeaders(key, { Prefer: 'return=representation' }),
      body: JSON.stringify({
        code:            newMemberCode(),
        name:            (user.name || user.email.split('@')[0]).slice(0, 120),
        email:           user.email,
        auth_user_id:    user.id,
        whatsapp:        '',
        duration:        36500,
        status:          'active',
        tier:            'free',
        free_started_at: now,
        expires_at:      '2099-12-31',
        last_login:      now,
        notes:           'Akun gratis',
      }),
    });
    if (r.ok) {
      const rows = await r.json();
      return res.status(200).json({ ok: true, member: toPublicMember(rows[0], user) });
    }
    if (r.status !== 409) {
      console.error('[login:start-free]', r.status, await r.text());
      return res.status(200).json({ ok: false, status: 'error' });
    }
    // 409: kode bentrok (coba kode lain) atau akun sudah dibuat oleh permintaan paralel.
    const existing = await resolveMember(user);
    if (existing) return res.status(200).json({ ok: true, member: toPublicMember(existing, user) });
  }
  return res.status(200).json({ ok: false, status: 'error' });
}

// Alamat aplikasi untuk redirect setelah bayar. APP_URL (opsional) menang; selain itu host permintaan.
const appOrigin = (req) => {
  const fixed = (process.env.APP_URL || '').trim().replace(/\/+$/, '');
  if (/^https:\/\//i.test(fixed)) return fixed;
  const host = String(req.headers['x-forwarded-host'] || req.headers.host || '').split(',')[0].trim();
  return /^[a-z0-9.-]+(:\d+)?$/i.test(host) ? `${host.startsWith('localhost') ? 'http' : 'https'}://${host}` : null;
};

const checkoutAttempts = new Map();
const checkCheckoutLimit = (key) => {
  const now = Date.now();
  const recent = (checkoutAttempts.get(key) || []).filter(t => now - t < 10 * 60 * 1000);
  if (recent.length >= 12) return false;
  recent.push(now);
  checkoutAttempts.set(key, recent);
  return true;
};

const publicCheckout = (c) => ({ id: c.id, plan: c.plan, amount: c.amount, link: c.link, status: c.status });

// Buat tagihan Mayar untuk paket yang dipilih (harga ditentukan server, bukan browser).
async function handleCheckout(req, user, res) {
  if (!mayarConfigured()) return res.status(200).json({ ok: false, status: 'payments_disabled' });
  const { plan } = await parseBody(req);
  if (!CHECKOUT_PLANS.includes(plan)) return res.status(400).json({ ok: false, status: 'invalid_plan' });
  if (!checkCheckoutLimit(user.id)) return res.status(429).json({ ok: false, status: 'rate_limited' });

  const member = await resolveMember(user);
  if (member && member.status !== 'active') return res.status(200).json({ ok: false, status: member.status });
  const blocked = checkoutBlockReason(plan, member);
  if (blocked) return res.status(200).json({ ok: false, status: blocked });

  const result = await createCheckout({ user, member, plan, appOrigin: appOrigin(req) });
  if (!result.ok) return res.status(200).json(result);
  return res.status(200).json({ ok: true, checkout: publicCheckout(result.checkout) });
}

// Dipanggil berkala selama pembeli menunggu. Kalau Mayar sudah lunas, akses langsung diaktifkan.
async function handleCheckoutStatus(req, user, res) {
  const { id } = await parseBody(req);
  const checkout = await getOwnedCheckout(id, user.id);
  if (!checkout) return res.status(404).json({ ok: false, status: 'not_found' });
  let status = checkout.status;
  try {
    status = await refreshCheckout(checkout);
  } catch (err) {
    console.warn('[login:checkout-status]', err.message);
  }
  return res.status(200).json({ ok: true, status, plan: checkout.plan });
}

async function handleUnsubscribe(req, res) {
  const email = String(req.query?.e || '').trim().toLowerCase();
  const ok = email.includes('@') && verifyUnsubToken(email, req.query?.t) && await addOptout(email).catch(() => false);
  if (req.method === 'POST') return res.status(ok ? 200 : 400).json({ ok });
  res.setHeader('Content-Type', 'text/html; charset=utf-8');
  const msg = ok
    ? 'Kamu tidak akan menerima email dari Talqeeh lagi. Akunmu tetap aktif seperti biasa.'
    : 'Link ini tidak valid atau sudah kedaluwarsa. Balas email dari Talqeeh bila ingin berhenti menerima email.';
  return res.status(ok ? 200 : 400).send(`<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Talqeeh</title></head><body style="font-family:system-ui,sans-serif;background:#0c0c0c;color:#eee;display:flex;min-height:100vh;align-items:center;justify-content:center;margin:0;padding:16px"><div style="max-width:420px;text-align:center"><h1 style="font-size:20px">${ok ? 'Berhasil berhenti berlangganan' : 'Gagal memproses'}</h1><p style="color:#aaa;line-height:1.6">${msg}</p><a href="/" style="color:#3ecf8e">Kembali ke Talqeeh</a></div></body></html>`);
}

/* ── Corong konversi (migrations/funnel_events.sql) ──
   Boleh tanpa login: kunjungan pertama belum punya akun. Hanya event & detail dari daftar tetap, ID pengunjung acak,
   dan satu baris per pengunjung/event/hari (unique + ignore-duplicates), jadi tabel tidak bisa dibanjiri isian bebas. */
const FUNNEL_EVENTS = ['visit', 'view_gabung', 'view_join', 'view_ai_partner', 'paywall', 'click_pay'];
const trackAttempts = new Map();
const checkTrackLimit = (key) => {
  const now = Date.now();
  const recent = (trackAttempts.get(key) || []).filter(t => now - t < 15 * 60 * 1000);
  if (recent.length >= 60) return false;
  recent.push(now);
  trackAttempts.set(key, recent);
  return true;
};

async function handleTrack(req, res) {
  const body = req.body || {};
  const event = String(body.event || '');
  const visitor = String(body.visitor || '');
  const detail = String(body.detail || '');
  if (!FUNNEL_EVENTS.includes(event) || !/^[a-z0-9]{12,40}$/.test(visitor) || !/^[a-z_]{0,30}$/.test(detail)) {
    return res.status(400).json({ ok: false });
  }
  const ip = (req.headers['x-forwarded-for'] || '').split(',')[0].trim() || 'unknown';
  if (!checkTrackLimit(ip)) return res.status(429).json({ ok: false });
  // Pengunjung yang sudah login dikaitkan ke kode membernya (untuk melihat siapa yang macet di tahap mana).
  const { url, key } = sbConfig();
  let memberCode = null;
  if (req.headers.authorization) {
    try {
      const user = await getAuthUser(req);
      if (user) {
        // Baca saja (resolveMember bisa menautkan email — efek samping yang tidak pantas untuk pencatatan).
        const m = await fetch(`${url}/rest/v1/members?auth_user_id=eq.${encodeURIComponent(user.id)}&select=code&limit=1`, { headers: sbHeaders(key) });
        if (m.ok) memberCode = (await m.json())?.[0]?.code || null;
      }
    } catch {}
  }
  const r = await fetch(`${url}/rest/v1/funnel_events?on_conflict=day,event,detail,visitor`, {
    method: 'POST',
    headers: sbHeaders(key, { Prefer: 'resolution=ignore-duplicates,return=minimal' }),
    body: JSON.stringify({ event, detail, visitor, member_code: memberCode }),
  });
  // Tabel belum dibuat → diam saja; pencatatan tidak boleh mengganggu pengguna.
  return res.status(200).json({ ok: r.ok });
}

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');

  if (req.method === 'OPTIONS') { res.status(204).end(); return; }
  const action = req.query?.action || 'session';
  // Link "berhenti menerima email" (GET dari email, POST satu-klik dari Gmail/Outlook) — tanpa login.
  if (action === 'unsubscribe') return await handleUnsubscribe(req, res);
  if (req.method !== 'POST') { res.status(405).json({ error: 'Method not allowed' }); return; }

  try {
    if (action === 'track') return await handleTrack(req, res);
    const user = await getAuthUser(req);
    if (!user) return res.status(401).json({ ok: false, status: 'unauthenticated' });

    if (action === 'session') return await handleSession(user, res);
    if (action === 'redeem')  return await handleRedeem(req, user, res);
    if (action === 'start-free') return await handleStartFree(req, user, res);
    if (action === 'checkout') return await handleCheckout(req, user, res);
    if (action === 'checkout-status') return await handleCheckoutStatus(req, user, res);
    return res.status(400).json({ ok: false, error: 'Action tidak valid' });
  } catch (err) {
    console.error(`[login:${action}]`, err.message);
    return res.status(500).json({ ok: false, status: 'error' });
  }
}
