import { sbConfig, sbHeaders, getAuthUser, resolveMember } from './_lib/member.js';
import { normalizePin } from './_lib/pin.js';

// Identity comes from the Supabase (Google) access token. Existing members link their
// Google account once via action=redeem with a one-time activation PIN generated by admin.
// Member codes are internal IDs only — they were often shared, so they can't claim an account.

const MEMBER_FIELDS = 'code,name,email,status,expires_at,auth_user_id,activation_pin_expires_at';

const redeemAttempts = new Map();
const checkRedeemLimit = (key) => {
  const now = Date.now();
  const recent = (redeemAttempts.get(key) || []).filter(t => now - t < 15 * 60 * 1000);
  if (recent.length >= 10) return false;
  recent.push(now);
  redeemAttempts.set(key, recent);
  return true;
};

const parseBody = (req) => new Promise((resolve) => {
  let body = '';
  req.on('data', chunk => body += chunk);
  req.on('end', () => {
    try { resolve(JSON.parse(body || '{}')); }
    catch { resolve({}); }
  });
});

const toPublicMember = (m, user) => ({
  code:      m.code,
  name:      m.name || user.name || user.email.split('@')[0],
  email:     m.email || user.email,
  status:    m.status,
  expiresAt: m.expires_at,
});

const touchLastLogin = (code) => {
  const { url, key } = sbConfig();
  fetch(`${url}/rest/v1/members?code=eq.${encodeURIComponent(code)}`, {
    method: 'PATCH',
    headers: sbHeaders(key, { Prefer: 'return=minimal' }),
    body: JSON.stringify({ last_login: new Date().toISOString() }),
  }).catch(e => console.warn('[login] last_login update failed:', e.message));
};

async function handleSession(user, res) {
  const member = await resolveMember(user);
  if (!member) return res.status(200).json({ ok: false, status: 'not_member', email: user.email });
  if (member.status !== 'active') return res.status(200).json({ ok: false, status: member.status });
  touchLastLogin(member.code);
  return res.status(200).json({ ok: true, member: toPublicMember(member, user) });
}

async function handleRedeem(req, user, res) {
  const ip = (req.headers['x-forwarded-for'] || '').split(',')[0].trim() || req.headers['x-real-ip'] || 'unknown';
  if (!checkRedeemLimit(`user:${user.id}`) || (ip !== 'unknown' && !checkRedeemLimit(`ip:${ip}`))) {
    return res.status(429).json({ ok: false, status: 'rate_limited' });
  }

  const pin = normalizePin((await parseBody(req)).pin);
  if (!pin) return res.status(400).json({ ok: false, status: 'invalid' });

  const current = await resolveMember(user);
  if (current?.status === 'active') {
    return res.status(200).json({ ok: true, member: toPublicMember(current, user) });
  }

  const { url, key } = sbConfig();
  const rows = await fetch(
    `${url}/rest/v1/members?activation_pin=eq.${encodeURIComponent(pin)}&select=${MEMBER_FIELDS}&limit=1`,
    { headers: sbHeaders(key) }
  ).then(r => r.json());
  const row = Array.isArray(rows) ? rows[0] : null;

  if (!row) return res.status(200).json({ ok: false, status: 'not_found' });
  if (row.activation_pin_expires_at && new Date(row.activation_pin_expires_at) < new Date()) {
    return res.status(200).json({ ok: false, status: 'pin_expired' });
  }
  if (row.status !== 'active') return res.status(200).json({ ok: false, status: row.status });
  if (row.auth_user_id && row.auth_user_id !== user.id) {
    return res.status(200).json({ ok: false, status: 'already_linked' });
  }

  // Conditional on the PIN still being unused and the row unlinked, so two accounts racing can't both win.
  // The PIN is cleared in the same update, making it single-use.
  const link = (patch) => fetch(
    `${url}/rest/v1/members?code=eq.${encodeURIComponent(row.code)}&activation_pin=eq.${encodeURIComponent(pin)}&auth_user_id=is.null&select=${MEMBER_FIELDS}`,
    {
      method: 'PATCH',
      headers: sbHeaders(key, { Prefer: 'return=representation' }),
      body: JSON.stringify({
        auth_user_id: user.id,
        activation_pin: null,
        activation_pin_expires_at: null,
        last_login: new Date().toISOString(),
        ...patch,
      }),
    }
  );

  let r = await link(row.email ? {} : { email: user.email });
  if (!r.ok) r = await link({}); // email already used by another member row
  const linked = await r.json().catch(() => []);
  if (!Array.isArray(linked) || !linked[0]) return res.status(200).json({ ok: false, status: 'already_linked' });

  return res.status(200).json({ ok: true, member: toPublicMember(linked[0], user) });
}

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');

  if (req.method === 'OPTIONS') { res.status(204).end(); return; }
  if (req.method !== 'POST') { res.status(405).json({ error: 'Method not allowed' }); return; }

  const action = req.query?.action || 'session';

  try {
    const user = await getAuthUser(req);
    if (!user) return res.status(401).json({ ok: false, status: 'unauthenticated' });

    if (action === 'session') return await handleSession(user, res);
    if (action === 'redeem')  return await handleRedeem(req, user, res);
    return res.status(400).json({ ok: false, error: 'Action tidak valid' });
  } catch (err) {
    console.error(`[login:${action}]`, err.message);
    return res.status(500).json({ ok: false, status: 'error' });
  }
}
